trigger:
- main

variables:
  envName: 'Pipeline-Level'   # Lowest precedence

stages:
- stage: BuildStage
  variables:
    envName: 'Stage-Level'    # Overrides pipeline

  jobs:
  - job: BuildJob
    variables:
      envName: 'Job-Level'    # Overrides stage & pipeline

    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Environment: $(envName)"  # Should print Job-Level

    - script: echo "Task override example"
      env:
        envName: 'Task-Level'             # Highest precedence

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Environment from overridden task: $envName"
